import { createApp, ref, computed, onMounted } from 'vue'
import './style.css'

type Course = { id:number; title:string; subject:string; grade:string; status:string; scenes:number; updatedAt:string }
const seed: Course[] = [{id:1,title:'牛顿第二定律',subject:'物理',grade:'高一',status:'PUBLISHED',scenes:4,updatedAt:'2026-09-11 09:00'}]
const load = (): Course[] => JSON.parse(localStorage.getItem('zhixue-courses') || JSON.stringify(seed))
const save = (v:Course[]) => localStorage.setItem('zhixue-courses', JSON.stringify(v))

const App = { setup() {
  const courses = ref<Course[]>(load()), topic = ref(''), loading = ref(false), message = ref(''), page = ref<'home'|'generate'|'lesson'>('home'), apiOnline = ref(false)
  const current = computed(() => courses.value[0])
  const flash = (m:string) => { message.value=m; setTimeout(()=>message.value='',2200) }
  const api = async (path:string, init?:RequestInit) => { const res=await fetch('/api/v1'+path, {...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}}); if(!res.ok) throw new Error('API '+res.status); return res.json() }
  onMounted(async()=>{ try { const body=await api('/courses'); if(Array.isArray(body.data)){ courses.value=body.data; apiOnline.value=true } } catch { apiOnline.value=false } })
  const generate = async () => { if (!topic.value.trim()) return flash('请输入课程主题'); loading.value=true; try { const body=await api('/courses',{method:'POST',body:JSON.stringify({title:topic.value.trim(),subject:'待设置',grade:'待设置'})}); if(body.data){ courses.value=[body.data,...courses.value.filter(c=>c.id!==body.data.id)]; apiOnline.value=true } } catch { const now=new Date().toLocaleString('zh-CN',{hour12:false}); const item:Course={id:Date.now(),title:topic.value.trim(),subject:'待设置',grade:'待设置',status:'DRAFT',scenes:4,updatedAt:now}; courses.value=[item,...courses.value]; save(courses.value) } finally { loading.value=false; page.value='lesson'; flash('课堂草稿已保存，可再次打开') } }
  const remove = async (id:number) => { try { await api('/courses/'+id,{method:'DELETE'}); apiOnline.value=true } catch {} courses.value=courses.value.filter(c=>c.id!==id); save(courses.value); flash('课程已删除') }
  const open = (c:Course) => { courses.value=[c,...courses.value.filter(x=>x.id!==c.id)]; page.value='lesson' }
  return {courses,topic,loading,message,page,current,generate,remove,open}
}, template:`<div class="app"><aside><div class="brand"><b>智</b><span>智学<small>Demo 0.2</small></span></div><nav><button :class="{active:page==='home'}" @click="page='home'">⌂ 工作台</button><button :class="{active:page==='generate'}" @click="page='generate'">✦ 生成课堂</button><button :class="{active:page==='lesson'}" @click="page='lesson'">▣ 互动课堂</button></nav><div class="note">Demo 0.2<br/>{{apiOnline?'已连接业务后端':'离线演示模式：本地保存'}}<br/>课程数据可刷新后再次打开。</div></aside><main><header><span>工作台 / <b>{{page==='home'?'概览':page==='generate'?'生成课堂':'互动课堂'}}</b></span><i>● {{apiOnline?'业务服务在线':'本地演示在线'}}</i></header><section v-if="page==='home'"><div class="hero"><div><h1>把每一节课，变成一次互动探索</h1><p>输入主题，生成可保存的互动课堂草稿。</p></div><button class="primary" @click="page='generate'">开始生成课堂 →</button></div><h2>最近课堂 <small>{{courses.length}} 门</small></h2><div class="grid"><article v-for="c in courses" :key="c.id" class="card"><span class="tag">{{c.status==='PUBLISHED'?'已发布':'草稿'}}</span><h3>{{c.title}}</h3><p>{{c.subject}} · {{c.grade}} · {{c.scenes}} 个场景</p><div class="bar"><em :style="{width:c.status==='PUBLISHED'?'100%':'28%'}"></em></div><footer><span>{{c.updatedAt}}</span><span class="actions"><button @click="open(c)">打开</button><button @click="remove(c.id)">删除</button></span></footer></article></div></section><section v-else-if="page==='generate" class="panel"><h2>生成一间互动课堂</h2><p>输入主题后保存为课程草稿，刷新页面数据仍然保留。</p><div class="form"><input v-model="topic" @keyup.enter="generate" placeholder="例如：光合作用的过程与意义"/><button class="primary" :disabled="loading" @click="generate">{{loading?'生成中…':'生成并保存'}}</button></div><div class="chips"><button v-for="x in ['牛顿第二定律','光合作用','二次函数']" @click="topic=x">{{x}}</button></div><div class="steps"><div>1　分析主题与教学目标</div><div>2　生成 4 个互动场景</div><div>3　保存课程草稿，可再次打开</div></div></section><section v-else class="lesson panel"><div class="lesson-head"><div><h2>{{current?.title}}</h2><p>互动课堂 · 已从后端数据模型迁移</p></div><button @click="page='home'">返回工作台</button></div><div class="scene"><small>01 · 情境引入</small><h1>为什么这个主题值得探索？</h1><p>课堂内容已保存为课程和场景数据。Demo 0.2 已支持刷新后继续打开，下一步可接入真实 AI 生成。</p><div class="tags"><span>知识点</span><span>互动提问</span><span>即时测验</span></div></div><button class="primary" @click="$event=>alert('Demo 0.2：测验模块将在下一迭代接入')">进入测验</button></section><div v-if="message" class="toast">{{message}}</div></main></div>`}
createApp(App).mount('#app')
